In [1]:
import pandas as pd

In [3]:
fortune = pd.read_csv('csv_files/fortune1000.csv', index_col='Rank')
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [4]:
sectors = fortune.groupby('Sector')
type(sectors)

pandas.api.typing.DataFrameGroupBy

In [ ]:
len(sectors) #There are 21 unique sectors

21

In [6]:
fortune['Sector'].nunique()

21

In [8]:
sectors.size()

Sector
Aerospace & Defense              20
Apparel                          15
Business Services                51
Chemicals                        30
Energy                          122
Engineering & Construction       26
Financials                      139
Food and Drug Stores             15
Food, Beverages & Tobacco        43
Health Care                      75
Hotels, Resturants & Leisure     25
Household Products               28
Industrials                      46
Materials                        43
Media                            25
Motor Vehicles & Parts           24
Retailing                        80
Technology                      102
Telecommunications               15
Transportation                   36
Wholesalers                      40
dtype: int64

In [ ]:
sectors.first() #sample row from top or bottom with last()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,Boeing,Aerospace and Defense,"Chicago, IL",96114,5176,161400
Apparel,Nike,Apparel,"Beaverton, OR",30601,3273,62600
Business Services,ManpowerGroup,Temporary Help,"Milwaukee, WI",19330,419,27000
Chemicals,Dow Chemical,Chemicals,"Midland, MI",48778,7685,49495
Energy,Exxon Mobil,Petroleum Refining,"Irving, TX",246204,16150,75600
Engineering & Construction,Fluor,"Engineering, Construction","Irving, TX",18114,413,38758
Financials,Berkshire Hathaway,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
Food and Drug Stores,CVS Health,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
"Food, Beverages & Tobacco",Archer Daniels Midland,Food Production,"Chicago, IL",67702,1849,32300
Health Care,McKesson,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
"Hotels, Resturants & Leisure",McDonald’s,Food Services,"Oak Brook, IL",25413,4529,420000
Household Products,Procter & Gamble,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
Industrials,General Electric,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
Materials,Alcoa,Metals,"New York, NY",22534,-322,60000
Media,Disney,Entertainment,"Burbank, CA",52465,8382,185000
Motor Vehicles & Parts,General Motors,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
Retailing,Walmart,General Merchandisers,"Bentonville, AR",482130,14694,2300000
Technology,Apple,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
Telecommunications,AT&T,Telecommunications,"Dallas, TX",146801,13345,281450
Transportation,UPS,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
Wholesalers,Sysco,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700

In [10]:
sectors.groups

{'Aerospace & Defense': [24, 45, 60, 88, 118, 120, 209, 245, 282, 378, 389, 490, 560, 605, 785, 788, 836, 903, 958, 987], 'Apparel': [91, 231, 340, 354, 448, 547, 575, 597, 683, 695, 726, 794, 877, 882, 917], 'Business Services': [144, 186, 199, 204, 221, 248, 249, 294, 307, 312, 355, 392, 404, 440, 467, 468, 481, 485, 492, 503, 545, 626, 635, 652, 677, 694, 714, 729, 734, 735, 737, 744, 767, 776, 777, 783, 791, 792, 796, 801, 803, 816, 819, 820, 869, 870, 886, 939, 951, 952, 993], 'Chemicals': [56, 101, 182, 189, 206, 253, 262, 277, 288, 296, 316, 538, 549, 555, 566, 580, 613, 624, 654, 668, 717, 720, 724, 758, 761, 829, 865, 898, 934, 949], 'Energy': [2, 14, 30, 32, 42, 65, 90, 95, 98, 104, 115, 117, 121, 162, 163, 165, 166, 175, 178, 188, 190, 192, 193, 198, 214, 216, 217, 223, 225, 229, 243, 246, 247, 257, 272, 274, 279, 289, 319, 322, 324, 343, 348, 349, 350, 363, 364, 384, 387, 388, 394, 402, 403, 410, 425, 437, 438, 445, 458, 475, 483, 493, 507, 522, 541, 548, 556, 558, 569, 571, 579, 598, 600, 606, 633, 650, 656, 662, 679, 692, 696, 703, 703, 706, 711, 715, 732, 742, 743, 745, 754, 772, 784, 798, 802, 810, 817, 826, 843, 850, ...], 'Engineering & Construction': [155, 156, 235, 260, 301, 314, 352, 381, 433, 478, 498, 501, 516, 572, 576, 640, 719, 738, 822, 863, 874, 892, 929, 963, 985, 994], 'Financials': [4, 16, 23, 26, 27, 29, 35, 40, 43, 49, 50, 61, 69, 73, 74, 76, 78, 81, 82, 83, 85, 100, 105, 112, 114, 131, 135, 137, 152, 171, 179, 184, 205, 210, 222, 226, 227, 232, 236, 250, 252, 259, 264, 265, 271, 273, 275, 283, 298, 306, 311, 318, 326, 329, 332, 344, 347, 367, 368, 376, 382, 398, 401, 411, 421, 436, 442, 449, 453, 453, 471, 472, 472, 476, 479, 482, 486, 488, 494, 497, 499, 506, 509, 510, 520, 529, 531, 536, 540, 551, 561, 568, 573, 590, 603, 609, 611, 646, 651, 663, ...], 'Food and Drug Stores': [7, 17, 19, 87, 107, 160, 181, 595, 614, 631, 669, 756, 809, 849, 928], 'Food, Beverages & Tobacco': [41, 44, 62, 66, 84, 94, 106, 149, 153, 161, 176, 207, 215, 242, 266, 304, 336, 337, 362, 397, 413, 429, 452, 456, 460, 535, 542, 567, 574, 587, 608, 615, 636, 664, 686, 702, 770, 787, 795, 804, 889, 902, 954], 'Health Care': [5, 6, 12, 21, 22, 33, 39, 46, 52, 55, 63, 72, 79, 86, 123, 124, 125, 130, 138, 140, 141, 168, 172, 200, 201, 202, 263, 268, 278, 286, 287, 290, 291, 305, 325, 358, 359, 372, 420, 430, 431, 447, 457, 465, 469, 515, 527, 537, 553, 559, 583, 618, 629, 661, 684, 693, 697, 708, 746, 749, 766, 775, 790, 799, 815, 818, 845, 868, 881, 883, 935, 960, 965, 977, 978], 'Hotels, Resturants & Leisure': [109, 146, 195, 218, 241, 254, 309, 371, 444, 466, 534, 546, 557, 562, 585, 731, 763, 764, 779, 797, 895, 915, 918, 941, 999], 'Household Products': [34, 151, 174, 256, 261, 328, 338, 345, 370, 434, 441, 450, 455, 533, 550, 554, 601, 665, 699, 716, 856, 890, 900, 907, 932, 950, 967, 992], 'Industrials': [11, 59, 75, 93, 97, 128, 134, 148, 211, 224, 360, 377, 396, 412, 419, 539, 544, 596, 622, 623, 630, 645, 655, 658, 666, 674, 690, 757, 782, 789, 806, 813, 823, 831, 832, 835, 841, 847, 866, 867, 873, 887, 942, 947, 964, 1000], 'Materials': [126, 127, 170, 244, 251, 303, 321, 341, 356, 373, 375, 383, 417, 418, 426, 435, 446, 480, 489, 514, 518, 577, 586, 616, 617, 620, 625, 628, 637, 639, 641, 660, 667, 687, 691, 751, 774, 793, 857, 885, 911, 982, 986], 'Media': [53, 96, 99, 203, 213, 255, 327, 366, 406, 414, 525, 530, 681, 705, 707, 722, 741, 752, 759, 762, 821, 913, 968, 969, 989], 'Motor Vehicles & Parts': [8, 9, 70, 147, 154, 169, 281, 310, 334, 339, 424, 428, 470, 588, 591, 604, 647, 670, 718, 739, 811, 957, 961, 979], 'Retailing': [1, 15, 28, 38, 47, 71, 89, 103, 111, 132, 136, 139, 143, 145, 177, 180, 191, 196, 197, 228, 234, 237, 238, 240, 258, 267, 269, 280, 293, 297, 299, 302, 330, 342, 346, 361, 365, 374, 379, 380, 393, 415, 427, 439, 495, 500, 502, 511, 512, 517, 523, 582, 592, 602, 607, 610, 621, 643, 644, 648, 657, 675, 689, 721, 748, 771, 773, 807, 812, 824, 825, 827, 840, 876, 894, 899, 922, 937, 940, 973], 'Technology': [3, 18, 20, 25, 31, 36, 51, 54, 77, 110, 113, 133, 150, 157, 158, 164, 173, 194, 219, 220, 230, 233, 284, 295, 300, 308, 313, 331, 385, 386, 400, 408, 409, 422, 451, 462, 464, 487, 491, 504, 505, 508, 513, 519, 524, 532, 543, 552, 563, 565, 584, 589, 593, 594, 612, 632, 634, 638, 649, 659, 673, 676, 678, 682, 688, 700, 725, 733, 736, 753, 760, 769, 778, 805, 830, 834, 842, 854, 864, 871, 888, 891, 893, 896, 904, 905, 906, 909, 912, 914, 919, 927, 931, 943, 944, 946, 956, 970, 971, 975, ...], 'Telecommunications': [10, 13, 37, 116, 159, 187, 292, 333, 399, 443, 461, 496, 526, 619, 786], 'Transportation': [48, 58, 67, 68, 80, 129, 142, 208, 239, 270, 353, 390, 395, 405, 407, 416, 432, 459, 521, 528, 570, 578, 642, 672, 709, 713, 740, 800, 814, 858, 884, 930, 933, 945, 972, 974], 'Wholesalers': [57, 64, 92, 102, 108, 119, 122, 167, 183, 185, 212, 276, 285, 315, 317, 320, 323, 335, 351, 357, 369, 391, 423, 463, 474, 477, 484, 564, 581, 599, 627, 653, 685, 727, 747, 780, 808, 837, 875, 991]}

In [13]:
fortune.loc[987]

Company      Delta Tucker Holdings
Sector         Aerospace & Defense
Industry     Aerospace and Defense
Location                McLean, VA
Revenue                       1923
Profits                       -133
Employees                    12000
Name: 987, dtype: object

In [ ]:
sectors.get_group('Energy') #subset method

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
14,Chevron,Energy,Petroleum Refining,"San Ramon, CA",131118,4587,61500
30,Phillips 66,Energy,Petroleum Refining,"Houston, TX",87169,4227,14000
32,Valero Energy,Energy,Petroleum Refining,"San Antonio, TX",81824,3990,10103
42,Marathon Petroleum,Energy,Petroleum Refining,"Findlay, OH",64566,2852,45440
...,...,...,...,...,...,...,...
981,WPX Energy,Energy,"Mining, Crude-Oil Production","Tulsa, OK",1958,-1727,1040
983,Adams Resources & Energy,Energy,Petroleum Refining,"Houston, TX",1944,-1,809
995,EP Energy,Energy,"Mining, Crude-Oil Production","Houston, TX",1908,-3748,665
997,Portland General Electric,Energy,Utilities: Gas and Electric,"Portland, OR",1898,172,2646
997,Portland General Electric,Energy,Utilities: Gas and Electric,"Portland, OR",1898,172,2646

In [21]:
sectors['Revenue'].sum()
sectors['Profits'].min()

Sector
Aerospace & Defense              -240
Apparel                            82
Business Services               -1481
Chemicals                        -816
Energy                         -23119
Engineering & Construction       -155
Financials                      -1194
Food and Drug Stores              -62
Food, Beverages & Tobacco        -253
Health Care                      -458
Hotels, Resturants & Leisure    -1394
Household Products              -1149
Industrials                     -6126
Materials                       -1642
Media                            -881
Motor Vehicles & Parts           -889
Retailing                       -1243
Technology                      -4359
Telecommunications               -271
Transportation                   -191
Wholesalers                      -502
Name: Profits, dtype: int64

In [24]:
sectors_industry = fortune.groupby(['Sector', 'Industry'])
sectors_industry.size()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            20
Apparel              Apparel                                          15
Business Services    Advertising, marketing                            2
                     Diversified Outsourcing Services                 14
                     Education                                         3
                                                                      ..
Transportation       Trucking, Truck Leasing                           9
Wholesalers          Miscellaneous                                     1
                     Wholesalers: Diversified                         25
                     Wholesalers: Electronics and Office Equipment     8
                     Wholesalers: Food and Grocery                     6
Length: 79, dtype: int64

.agg Method

In [25]:
sectors.agg({'Revenue':'sum', 'Profits':'sum', 'Employees' : 'mean'})

                              Revenue  Profits     Employees
Sector
Aerospace & Defense            357940    28742  48402.850000
Apparel                         95968     8236  23093.133333
Business Services              272195    28227  26687.254902
Chemicals                      243897    22628  15455.033333
Energy                        1517809   -73447   9745.303279
Engineering & Construction     153983     5304  15642.615385
Financials                    2217159   260209  24172.287770
Food and Drug Stores           483769    16759  93026.533333
Food, Beverages & Tobacco      555967    51417  28177.488372
Health Care                   1614707   106114  35710.520000
Hotels, Resturants & Leisure   169546    20697  99369.800000
Household Products             234737    14428  23072.785714
Industrials                    497581    20764  33591.934783
Materials                      259145     4428  14840.069767
Media                          220764    24347  22012.560000
Motor Vehicles & Parts         482540    25898  45106.666667
Retailing                     1465076    47830  77845.362500
Technology                    1377600   180473  35087.735294
Telecommunications             461834    48637  55497.866667
Transportation                 408508    44169  42688.694444
Wholesalers                    444800     8233  13139.925000

In [28]:
numeric_sectors = sectors.obj.select_dtypes(include='number').columns
sectors[numeric_sectors].agg(['size', 'sum', 'mean'])

                             Revenue                        Profits          \
                                size      sum          mean    size     sum
Sector
Aerospace & Defense               20   357940  17897.000000      20   28742
Apparel                           15    95968   6397.866667      15    8236
Business Services                 51   272195   5337.156863      51   28227
Chemicals                         30   243897   8129.900000      30   22628
Energy                           122  1517809  12441.057377     122  -73447
Engineering & Construction        26   153983   5922.423077      26    5304
Financials                       139  2217159  15950.784173     139  260209
Food and Drug Stores              15   483769  32251.266667      15   16759
Food, Beverages & Tobacco         43   555967  12929.465116      43   51417
Health Care                       75  1614707  21529.426667      75  106114
Hotels, Resturants & Leisure      25   169546   6781.840000      25   20697
Household Products                28   234737   8383.464286      28   14428
Industrials                       46   497581  10816.978261      46   20764
Materials                         43   259145   6026.627907      43    4428
Media                             25   220764   8830.560000      25   24347
Motor Vehicles & Parts            24   482540  20105.833333      24   25898
Retailing                         80  1465076  18313.450000      80   47830
Technology                       102  1377600  13505.882353     102  180473
Telecommunications                15   461834  30788.933333      15   48637
Transportation                    36   408508  11347.444444      36   44169
Wholesalers                       40   444800  11120.000000      40    8233

                                          Employees
                                     mean      size      sum          mean
Sector
Aerospace & Defense           1437.100000        20   968057  48402.850000
Apparel                        549.066667        15   346397  23093.133333
Business Services              553.470588        51  1361050  26687.254902
Chemicals                      754.266667        30   463651  15455.033333
Energy                        -602.024590       122  1188927   9745.303279
Engineering & Construction     204.000000        26   406708  15642.615385
Financials                    1872.007194       139  3359948  24172.287770
Food and Drug Stores          1117.266667        15  1395398  93026.533333
Food, Beverages & Tobacco     1195.744186        43  1211632  28177.488372
Health Care                   1414.853333        75  2678289  35710.520000
Hotels, Resturants & Leisure   827.880000        25  2484245  99369.800000
Household Products             515.285714        28   646038  23072.785714
Industrials                    451.391304        46  1545229  33591.934783
Materials                      102.976744        43   638123  14840.069767
Media                          973.880000        25   550314  22012.560000
Motor Vehicles & Parts        1079.083333        24  1082560  45106.666667
Retailing                      597.875000        80  6227629  77845.362500
Technology                    1769.343137       102  3578949  35087.735294
Telecommunications            3242.466667        15   832468  55497.866667
Transportation                1226.916667        36  1536793  42688.694444
Wholesalers                    205.825000        40   525597  13139.925000

In [31]:
df = pd.DataFrame(columns = fortune.columns)
df

Empty DataFrame
Columns: [Company, Sector, Industry, Location, Revenue, Profits, Employees]
Index: []

In [34]:
# 1. Create an empty list
results_list = []

for sector, data in sectors:
    highest_revenue_company_in_group = data.nlargest(1, 'Revenue')
    # 2. Append the small DataFrame to the list
    results_list.append(highest_revenue_company_in_group)

# 3. Combine them all at once
df = pd.concat(results_list)
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
24,Boeing,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",96114,5176,161400
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
144,ManpowerGroup,Business Services,Temporary Help,"Milwaukee, WI",19330,419,27000
56,Dow Chemical,Chemicals,Chemicals,"Midland, MI",48778,7685,49495
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
155,Fluor,Engineering & Construction,"Engineering, Construction","Irving, TX",18114,413,38758
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
41,Archer Daniels Midland,"Food, Beverages & Tobacco",Food Production,"Chicago, IL",67702,1849,32300
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
109,McDonald’s,"Hotels, Resturants & Leisure",Food Services,"Oak Brook, IL",25413,4529,420000
34,Procter & Gamble,Household Products,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
11,General Electric,Industrials,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
126,Alcoa,Materials,Metals,"New York, NY",22534,-322,60000
53,Disney,Media,Entertainment,"Burbank, CA",52465,8382,185000
8,General Motors,Motor Vehicles & Parts,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
10,AT&T,Telecommunications,Telecommunications,"Dallas, TX",146801,13345,281450
48,UPS,Transportation,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
57,Sysco,Wholesalers,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700

In [36]:
cities = fortune.groupby('Location')
df = pd.DataFrame(columns = fortune.columns)
df

Empty DataFrame
Columns: [Company, Sector, Industry, Location, Revenue, Profits, Employees]
Index: []

In [41]:
result_list2 = []
for city,data in cities:
    highest_revenue_in_city = data.nlargest(1, 'Revenue')
    result_list2.append(highest_revenue_in_city)
df = pd.concat(result_list2)
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
138,Abbott Laboratories,Health Care,Medical Products and Equipment,"Abbott Park, IL",20661,4423,74000
169,Goodyear Tire & Rubber,Motor Vehicles & Parts,Motor Vehicles and Parts,"Akron, OH",16443,307,66000
288,Air Products & Chemicals,Chemicals,Chemicals,"Allentown, PA",9895,1278,19550
830,Benchmark Electronics,Technology,Semiconductors and Other Electronic Components,"Angleton, TX",2541,95,10500
374,Casey’s General Stores,Retailing,Specialty Retailers: Other,"Ankeny, IA",7052,181,22408
...,...,...,...,...,...,...,...
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
506,Hanover Insurance Group,Financials,Insurance: Property and Casualty (Stock),"Worcester, MA",5034,332,4800
764,Penn National Gaming,"Hotels, Resturants & Leisure","Hotels, Casinos, Resorts","Wyomissing, PA",2838,1,18204
773,Bon-Ton Stores,Retailing,General Merchandisers,"York, PA",2790,-57,24100
932,Herman Miller,Household Products,"Home Equipment, Furnishings","Zeeland, MI",2142,98,7510